POO2021/FRAMEWORK/ejemplos/prueba1/models/Contacto.php
<?php

namespace app\models;

use yii\base\Model;
use Yii;

Class Contacto extends Model{
    public $nombre;
    public $email;
    public $telefono;
    public $direccion;
    public $fecha;
    public $politica;
    public $asunto;


    public function attributeLabels(): array {
        return[
            
            "nombre" => "Nombre completo",
            "email" => "Correo electronico",
            "telefono" => "Telefono",
            "direccion" => "Direccion completa",
            "asunto"=> "Indique pregunta",
            "fecha" => "fecha Nacimiento",
            "politica"=> "comprobarpoliticas",
            
            
        ];

}
  public function rules(){
      return[
          [["nombre","email","telefono"],"required"],
          ["email","email"],
          ["nombre","string","length" =>[1,100]],
          ["politica",'boolean'],
         // ["fecha", "date","format yyyy-mm-dd" ],
          ["fecha", "string" ],
        [["direccion", "asunto"], "safe"],  
          
          ["politica","comprobarpoliticas"], // chequear si has aceptado las politica
          
          
          
          
      ];
      
  }
  
  /**
   * 
   * chequear que se han aceptado.
   */
  public function comprobarpoliticas($attribute,$params){
      if($this->attributes==0){
          $this->addError($attribute,"Es necesarioaceptar politicas");
      }
  }
  
  public function contact()
    {
        if ($this->validate()) {
            Yii::$app->mailer->compose()
                ->setTo(Yii::$app->params['contacto'])
                ->setFrom([Yii::$app->params['senderEmail'] => Yii::$app->params['senderName']])
                ->setReplyTo([$this->email => $this->nombre])
                ->setSubject("mandadon informacion")
                ->setTextBody($this->asunto)
                ->send();

            return true;
        }
        return false;
    }

}
          
      
      
      
  
      
        

POO2021/FRAMEWORK/ejemplos/prueba1/models/Productos.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "productos".
 *
 * @property int $id
 * @property string|null $nombre
 * @property string|null $foto
 * @property string|null $descripcion
 * @property float|null $precio
 * @property int|null $oferta
 * @property string|null $categorias
 */
class Productos extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'productos';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['precio'], 'number'],
            [['oferta'], 'integer'],
            [['nombre', 'foto', 'categoria'], 'string', 'max' => 100],
            [['descripcion'], 'string', 'max' => 800],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'foto' => 'Foto',
            'descripcion' => 'Descripcion',
            'precio' => 'Precio',
            'oferta' => 'Oferta',
            'categoria' => 'Categoria',
        ];
    }
}

POO2021/FRAMEWORK/ejemplos/prueba1/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Productos;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    /*public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }*/

    
    public function actionProductos() {
        $dataProvider=new ActiveDataProvider([
            'query'=> Productos::find()
              
     
        ]);
        
        return $this->render("productos",[
            "dataProvider" =>$dataProvider,
            
        ]);
        
    }
    
    public function actionNuestros() {
        $fotos= Productos::find()
            ->select("foto")
            ->where(["oferta"=>1])   
             ->asArray()
             ->all();
    
        
        $fotos= ArrayHelper::getColumn($fotos, "foto");
        
        $salida=[];
        foreach ($fotos as $src) {
            $salida[]=Html::img("@web/imgs/$src");
            
            
            
        }
        
        return $this->render("nuestros",[
            "fotos" =>$salida,
            
        ]);
        
    }
    
    public function actionOferta() {
        $dataProvider=new ActiveDataProvider([
            'query'=> Productos::find()->where(['oferta'=>1])
          
              
     
        ]);
         return $this->render("ofertas",[
            "dataProvider" =>$dataProvider,
             
             ]);
         
    }
          public function actionCategorias(){
        $dataProvider=new ActiveDataProvider([
            'query' => Productos::find()->select('categorias')->distinct()
        ]);
        
        return $this->render("categorias",[
            "dataProvider" => $dataProvider,
        ]);
        
          }
         public function actionVer($categoria){
        $productos=Productos::find()->where(['categorias'=>$categoria]);
       
        
        
        $dataProvider=new ActiveDataProvider([
            'query'=> $productos, 
        ]);
        
        return $this->render('ver',[
            'dataProvider'=>$dataProvider,
            'categoria'=>$categoria
        ]);
    }

        public function actionDonde(){
        return $this->render("donde");
        
        }
            
        public function actionQuienes(){
        return $this->render("quienes");
        }
        
        
        public function actionProductos2(){
        return $this->render("productos2");
        }
        
        
        public function actionContacto()
{
    $model = new \app\models\Contacto(); //objeto tipo contacto vacio
    
    
    
    if ($model->load(Yii::$app->request->post())) { /// leo los datos y enviado a datos
        if ($model->contact()) { // model es objeto  
            if($model->politica){
           
            return $this->render("Mostrar");
        }
    }
    }
    return $this->render('contacto', [
        'model' => $model,
    ]);
        
    }
    
     public function actionVermas($id){
    $salida=Productos::find()->where(["id"=>$id]);
     $salida=Productos::findOne($id);
     
     
     return $this->render("vermas",[
         "model" => $salida,
         
         
         
     ]);
} 
    /**
     * Displays about page.
     *
     * @return string
     */
   /*public function actionAbout()
    {
        return $this->render('about');
    }
    
    
    */


}

POO2021/FRAMEWORK/ejemplos/prueba1/views/site/_info.php
<?php
use yii\widgets\ListView;
?>

POO2021/FRAMEWORK/ejemplos/prueba1/views/site/_oferta.php
<?php
use yii\helpers\Html;
?>
<div class="row">
    <div class="col-lg-5">
    <?php
    echo Html::img("@web/imgs/$model->foto",[
    "class" =>"card-img-top"
    ]);
    
    ?>
    </div>
    <div class="col-lg-7">
        <h2><?= $model->nombre ?><br></h2>
        <div class="bg-warning rounded p-2">foto:</div>
        <div class="p-1"><?= $model->foto ?> foto</div>
        <div class="bg-warning rounded p-2">descripcion:</div>
        <div class="p-1"><?= substr ($model->descripcion,0,100) . "..." ?></div>
        <div class="bg-warning rounded p-2">Categoria:</div>
        <div class="p-1"><?= $model->categorias ?></div>
        
       <?= Html::a("Ver mas",["site/vermas","id"=>$model->id],["class"=>"Btn btn-primary float-right"])?>
            
         ?><br>
    </div>
    
</div>

POO2021/FRAMEWORK/ejemplos/prueba1/views/site/_ver.php
<?php
use yii\helpers\Html;
?>
<div class="row">
    <div class="col-lg-5">
    <?php
    echo Html::img("@web/imgs/$model->foto",[
    "class" =>"card-img-top"
    ]);
    
    ?>
    </div>
    <div class="col-lg-7">
        <h2><?= $model->nombre ?><br></h2>
        <div class="bg-warning rounded p-2">Foto:</div>
        <div class="p-1"><?= $model->foto ?></div>
        <div class="bg-warning rounded p-2">Descripción:</div>
        <div class="p-1"><?= $model->descripcion ?></div>
        <div class="bg-warning rounded p-2">Precio:</div>
        <div class="p-1"><?= $model->precio ?></div>
           
    </div>
    
</div>

POO2021/FRAMEWORK/ejemplos/prueba1/views/site/categorias.php
<?php
use yii\widgets\ListView;
?>

<h1 class="border rounded bg-secondary p-3 text-white text-center mb-5">Categorias</h1>
    
<?php
echo ListView::widget([
    "dataProvider" => $dataProvider,
    "itemView" => "_categorias",
    "itemOptions" => [
        'class' => 'col-lg-4',
    ],
    "options" => [
        'class' => 'row',
    ],
    'layout'=>"{items}"
]);

POO2021/FRAMEWORK/ejemplos/prueba1/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap4\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\captcha\Captcha;

$this->title = 'Contacto';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
           
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            Introduzca sus datos y le responderemos lo mas rapido posible.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                  
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

POO2021/FRAMEWORK/ejemplos/prueba1/views/site/donde.php
<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11583.807403746137!2d-3.8117277!3d43.4616024!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x7858c552ade0effc!2sAlpe%20Formaci%C3%B3n!5e0!3m2!1ses!2ses!4v1633948578829!5m2!1ses!2ses" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>


<div>
    pasaje Peña1<br>
    telefono <br>
    Cantabria<br>
    
</div>

POO2021/FRAMEWORK/ejemplos/prueba1/views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Prueba1';
?>
<div class="site-index">

    

   <div
                <h2>Heading</h2>

                <p>Nuestra pagina La Jota es la mejor en venta de productos</p>

                
            </div>
            

                
            </div>
       

POO2021/FRAMEWORK/ejemplos/prueba1/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap4\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 col-form-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"offset-lg-1 col-lg-3 custom-control custom-checkbox\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="offset-lg-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="offset-lg-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

POO2021/FRAMEWORK/ejemplos/prueba1/views/site/mostrar.php
Muchas gracias nos pondremos en contacto contigo.

POO2021/FRAMEWORK/ejemplos/prueba1/views/site/ofertas.php
<?php
use yii\widgets\ListView;
?>

<h1 class="border rounded bg-secondary p-3 text-white text-center mb-5">oferta</h1>
    <i class="fa fa-check" aria-hidden="true"> </i>


<?php
echo ListView::widget([
    "dataProvider" => $dataProvider,
    "itemView" => "_oferta",
    "options" => [
        'class' => 'row',
    ],
    'layout'=>"{items}",
    "itemOptions" => [
        'class' => 'col-lg-5 ml-auto mr-auto bg-light p-3 mb-5',
    ],

]);

POO2021/FRAMEWORK/ejemplos/prueba1/views/site/productos2.php
<p>hola</p>

POO2021/FRAMEWORK/ejemplos/prueba1/views/site/quienes.php
<p>Nuestra pagina La Jota es la mejor en venta de productos</p>

POO2021/FRAMEWORK/ejemplos/prueba1/views/site/ver.php
<?php
use yii\widgets\ListView;
?>
<h1 class="border rounded bg-secondary p-3 text-white text-center mb-5">Listado  de Productos <?= $categoria?></h1>
<?php
echo ListView::widget([
    "dataProvider" => $dataProvider,
    "itemView" => "_ver",
    "itemOptions" => [
        'class' => 'col-lg-5 ml-auto mr-auto bg-light p-3 mb-5',
    ],
    "options" => [
        'class' => 'row',
    ],
    'layout'=>"{items}"
]);

POO2021/FRAMEWORK/ejemplos/prueba1/views/site/vermas.php
<?php


use yii\widgets\DetailView;
use yii\helpers\Html;


echo DetailView::widget([
    'model' => $model,
    'attributes' => [
        'id',               // title attribute (in plain text)
        'description',
        'precio',
        'categoria',
        'oferta',
        
        [
          'label'=>'foto',
           'format'=>'Foto Producto',
            'value'=>function($data){
            $url ="@web/imgs/$data->foto";
            return Html::img($url,['style'=>'width:200px']);
    
    
            }
            
            
            
        ],
        'foto',// description attribute in HTML
        [                      // the owner name of the model
            'label' => 'Owner',
            'value' => $model->owner->name,
        ],
        'created_at:datetime', // creation date formatted as datetime
    ],
]);
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of vermas
 *
 * @author Programacion
 */