POO2021/FRAMEWORK/ejemplos/ejemplo7yii/models/User.php
<?php

namespace app\models;

class User extends \yii\base\BaseObject implements \yii\web\IdentityInterface
{
    public $id;
    public $username;
    public $password;
    public $authKey;
    public $accessToken;

    private static $users = [
        '100' => [
            'id' => '100',
            'username' => 'admin',
            'password' => 'admin',
            'authKey' => 'test100key',
            'accessToken' => '100-token',
        ],
        '101' => [
            'id' => '101',
            'username' => 'demo',
            'password' => 'demo',
            'authKey' => 'test101key',
            'accessToken' => '101-token',
        ],
    ];


    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return isset(self::$users[$id]) ? new static(self::$users[$id]) : null;
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        foreach (self::$users as $user) {
            if ($user['accessToken'] === $token) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        foreach (self::$users as $user) {
            if (strcasecmp($user['username'], $username) === 0) {
                return new static($user);
            }
        }

        return null;
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return $this->password === $password;
    }
}

POO2021/FRAMEWORK/ejemplos/ejemplo7yii/models/numeros3y4.php
<?php


namespace app\models;

use yii\base\Model;

class Numeros extends Model{
    public $numero1;
    public $numero2;
    public $tipo;
    public $ejercicio1;
    public $ejercicio2;
    public $ejercicio3;
    public $ejercicio4;
    
    public function attributeLabels(){
        return[
            "numero1"=>"Numero 1",
            "numero2"=>"Numero 2",
            "ejercicio1"=> "la secuencia es",
            "ejercicio2"=> "el patron es ",
            "ejercicio3"=> "el numero3 es mayor que el numero2",
            "ejercicio4"=> "el numero3 es mayor que el numero2",
            
            
        ];
            
    }
    
    public function rules(){
        return [
            [['numero1','numero2'],'integer'],
            [['numero1','numero2'],'required'],
            
            []
          /*  ['numero2', 'compare', 'compareValue' => 0, 'operator' => '!=', 'type' => 'number','when'=>function($model){
            $model->tipo=="dividir"; //solo relaiza la validad si la operacion es dividir.
            }]*/
            
            
    ];
    }
    /**
     * esta regla me comprueba cuando estoy diviendo que el numero2  no sea 0
     * @param type $atributo
     * @param type $parametros
     */
    public function dividirPorCero($atributo,$parametros){
        if($this->tipo=="dividir" || $this->tipo=="todo"){
            if($this->numero2==0){
                $this->addError("numero2", "No puede ser un 0 si se divide");
                
            }
            
        }
    }
            
    public function operacion (){
        switch ($this->tipo){
            
            case 'ejercicio1':
                return $this -> numero1;
                break;
            case 'ejercicio2':
                return $this -> numero1-$this->numero2;
                break;
             case 'ejercicio3':
                return $this -> numero3>$this->numero2;
                break;
             case 'ejercicio4':
                return $this -> numero3*$this->numero4;
                break;
            default:
                return 0;
        }
        
        
    }
    
    public function operarTodo(){
        
        $this->ejercicio1=$this->numero1+$this->numero2;
        $this->ejercicio2=$this->numero1-$this->numero2;
        $this->ejercicio3=$this->numero1*$this->numero2;
        $this->ejercicio4=$this->numero1/$this->numero2;
        
    }
}

POO2021/FRAMEWORK/ejemplos/ejemplo7yii/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionEjercicio1() {
       
    
    return $this->render (ejercicio1);
    
    
    }
       
 
}

POO2021/FRAMEWORK/ejemplos/ejemplo7yii/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header>
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-expand-md navbar-dark bg-dark fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'ejercicio1', 'url' => ['/site/ejercicio1']],
            ['label' => 'ejercicio2', 'url' => ['/site/ejercicio2']],
            ['label' => 'ejercicio3', 'url' => ['/site/ejercicio3']],
            ['label' => 'ejercicio4', 'url' => ['/site/ejercicio4']]
            
        ],
    ]);
    NavBar::end();
    ?>
</header>

<main role="main" class="flex-shrink-0">
    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<footer class="footer mt-auto py-3 text-muted">
    <div class="container">
        <p class="float-left">Compañia sanchez</p>
        <p class="float-right">2021</p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>